Validate the for format of the access_token and improve debug messages
MonolithProjects/ansible-github_actions_runner pull request #93
Opened 2021-08-01 19:37 UTC by Th0masL

# Pull Request Template

## Description

I had to deploy the role for the first time, and I originally faced some problems.

One of my problem was that I set `runner_org: yes` because I thought that it had to be set to this value if the repo is owned by an org.

I struggled to find the problem because I couldn't see which task was using the name `Get registration token (RUN ONCE)`, as such task was declared with the same name in two different files :
```
# grep -rni './' -e 'Get registration token (RUN ONCE)'
.//tasks/collect_info_repo.yml:3:  - name: Get registration token (RUN ONCE)
.//tasks/collect_info_org.yml:3:  - name: Get registration token (RUN ONCE)
```

The other problem I had was that I generated a token using the repository's Action page, which was not a valid Personal Access Token.

To reduce the probability of other people facing the same problem, I decided to improve a little bit the role by testing the format of the Personal Access Token, and also show in which mode we currently are `Org` vs `non-Org` mode.

List of the changes :
- make sure that the `access_token` match the format for Personal Access Token (should start with `ghp_`)
- updated some tasks' messages to show if we are running in 'Org mode' or 'non-Org mode'
- added debug task to show the version found

## Type of change

- [x] Basic improvements (non-breaking change which improve the usability of the role)

## How Has This Been Tested?

I tested the changes by deploying the role on my server, with different values for the `access_token`, ensuring that the role fails when the `access_token` is not respecting the correct format.

Example of error when the `access_token` does not match the Personal Access Token format :
```
TASK [monolithprojects.github_actions_runner : Check variables (RUN ONCE)] ******************************************************************************************
fatal: [server1]: FAILED! => {
    "assertion": "access_token | regex_search('^ghp_')",
    "changed": false,
    "evaluated_to": false,
    "msg": "access_token was not found or is invalid."
}
```

## Destination branch

Create a PR into `develop` branch

2021-08-02 14:09 UTC, MonolithProjects commented
Hey thanks @Th0masL . It looks good

2021-08-02 16:54 UTC, MonolithProjects requested changes

2021-08-03 22:03 UTC, Th0masL commented on tasks/install_runner.yml
> +name: Show the runner_version
Sorry about that, that should be fixed :)

2021-08-04 04:59 UTC, MonolithProjects approved these changes

2021-08-04 05:00 UTC, merged